backend:
  name: github
  repo: YOUR_GITHUB_USERNAME/picklephil-site   # ← change me
  branch: main
  base_url: https://YOUR-OAUTH-WORKER.workers.dev  # ← change me
  auth_endpoint: /auth

publish_mode: editorial_workflow

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "discgolf"
    label: "Disc Golf Hub"
    files:
      - file: "data/discgolf.json"
        label: "Disc Golf Data"
        name: "discgolf"
        fields:
          - { label: "Hero Title", name: "hero.title", widget: "string" }
          - { label: "Hero Tagline", name: "hero.tagline", widget: "string" }
          - label: "Bag"
            name: "bag"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Note", name: "note", widget: "string", required: false }
          - label: "Courses"
            name: "courses"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
          - label: "Latest Scorecard"
            name: "latest_scorecard"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Summary", name: "summary", widget: "string" }
              - { label: "Image URL (or static/latest-scorecard.png)", name: "image", widget: "string", required: false }
              - { label: "Date", name: "date", widget: "string" }
